<?xml version="1.0" encoding="utf-8"?><Database Name="HOP-db" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BISMILLAH-XD\SQLEXPRESS;Initial Catalog=HOP-db;Integrated Security=True" SettingsObjectName="HouseofPain.Properties.Settings" SettingsPropertyName="HOP_dbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Mship" Member="Mships">
    <Type Name="Mship">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pg" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="programme" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="sdate" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="price" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="sfee" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="nvisits" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="conditions" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IDD" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="edate" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="medate" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="state" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Mdetail" Member="Mdetails">
    <Type Name="Mdetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lname" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="gender" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="street" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="city" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="home" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="cell" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="cardn" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="workp" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="occu" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="org" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="invtype" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ptrain" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="email" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dp" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IDD" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="photo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dop" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>